#@ load("@ytt:data", "data")
---
apiVersion: v1
stringData:
  ca.crt: #@ data.values.other.sensitive_values.certs.appliveview.ca
  tls.crt: #@ data.values.other.sensitive_values.certs.appliveview.cert
  tls.key: #@ data.values.other.sensitive_values.certs.appliveview.key
kind: Secret
metadata:
  name: app-live-view-cert-manual
  namespace: app-live-view
type: kubernetes.io/tls
