apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossplane-missing-stuff
rules:
- apiGroups:
  - kubernetes.crossplane.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - helm.crossplane.io
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane-missing-stuff
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane-missing-stuff
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: crossplane
  namespace: crossplane-system