#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:yaml", "yaml")

---
apiVersion: v1
kind: Namespace
metadata:
  name: services

---
apiVersion: v1
kind: Secret
metadata:
  name: gitops-ssh
  namespace: services
  annotations:
    tekton.dev/git-0: #@ data.values.other.sensitive_values.gitlab.url
type: kubernetes.io/basic-auth
stringData:
  caFile: #@ data.values.other.sensitive_values.teams.teal.git.ca_cert_data
  password: #@ data.values.other.sensitive_values.teams.teal.gitlab.password
  username: #@ data.values.other.sensitive_values.teams.teal.gitlab.username

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: services
  namespace: apps
spec:
  interval: 5m0s
  path: ./teams/services/build
  prune: true
  targetNamespace: services
  sourceRef:
    kind: GitRepository
    name: apps