#@data/values-schema
#@overlay/match-child-defaults missing_ok=True
---
custom:
  tbs_full_dependencies:
    enabled: true
    pkgr_version: "1.10.10"
    pkgr_repo_url: harbor.services.mydomain.com/buildservice/tbs-full-deps
  