tap_install:
    sensitive_values:
        shared:
            image_registry:
                project_path: ...
                username: ...
                password: ...
        tap_gui:
            service_type: ...
            app_config:
                techdocs:
                    builder: ...
                    publisher:
                        type: ...
                        awsS3:
                            bucketName: ...
                            credentials:
                                accessKeyId: ...
                                secretAccessKey: ...
                            region: ...
                            s3ForcePathStyle: ...
                            forcePathStyle: ...
                            endpoint: ...
                catalog:
                    locations:
                        - type: ...
                          target: ...
                        - type: ...
                          target: ...
                    providers:
                        microsoftGraphOrg:
                            default:
                                clientId: ...
                                clientSecret: ...
                                tenantId: ...
                                user:
                                    filter: ...
                                group:
                                    filter: ...
                auth:
                    environment: ...
                    providers:
                        microsoft:
                            development:
                                clientId: ...
                                clientSecret: ...
                                tenantId: ...
                        gitlab:
                            development:
                                clientId: ...
                                clientSecret: ...
                                audience: ...
                integrations:
                    awsS3:
                        - endpoint: ...
                          s3ForcePathStyle: ...
                          forcePathStyle: ...
                          accessKeyId: ...
                          secretAccessKey: ...
                    gitea:
                        - host: ...
                          username: ...
                          password: ...
                    gitlab:
                        - host: ...
                          token: ...
                          apiBaseUrl: ...
                          baseUrl: ...
                kubernetes:
                    serviceLocatorMethod:
                        type: ...
                    clusterLocatorMethods:
                        - type: ...
                          clusters:
                            - url: ...
                              name: ...
                              authProvider: ...
                              serviceAccountToken: ...
                              skipTLSVerify: ...
                              skipMetricsLookup: ...
                            - url: ...
                              name: ...
                              authProvider: ...
                              serviceAccountToken: ...
                              skipTLSVerify: ...
                              skipMetricsLookup: ...
                            - url: ...
                              name: ...
                              authProvider: ...
                              serviceAccountToken: ...
                              skipTLSVerify: ...
                              skipMetricsLookup: ...
other:
    sensitive_values:
        certs:
            appliveview:
                cert: ...
                key: ...
                ca: ...
            metadata_store:
                cert: ...
                key: ...
                ca: ...
            gui:
                cert: ...
                key: ...
                ca: ...
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age...
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYYmhyWnJzTVdlT0ljc3hk
            ...
            KggRul43Pb9Tgy6sdS7LeURDmuTcUmO5fuhFAs41umG7FJsGQVxR0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T11:39:01Z"
    mac: ...
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
