#@data/values-schema
#@overlay/match-child-defaults missing_ok=True
---
custom:
  tbs_full_dependencies:
    enabled: true
    pkgr_version: "1.10.10"
    pkgr_repo_url: harbor.mydomain.com/buildservice/tbs-full-deps
  trivy:
    enabled: true
    pkgr_version: "0.1.6-alpha.4"
    pkgr_repo_url: harbor.mydomain.com/tap/trivy-repo-scanning-bundle