apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  interval: 3m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./platforms/clusters/services/flux-sources/namespaces
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  dependsOn:
    - name: namespaces
  interval: 3m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./platforms/clusters/services/flux-sources/secrets
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg