apiVersion: v1
data:
    password: ...
    user: ...
kind: Secret
metadata:
    creationTimestamp: null
    name: basic-auth
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-06-13T15:16:38Z"
    mac: ...
    pgp:
        - created_at: "2023-06-13T15:16:37Z"
          enc: |
            -----BEGIN PGP MESSAGE-----
            ...
            =DDQz
            -----END PGP MESSAGE-----
          fp: ...
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
