apiVersion: v1
data:
    password: ...
kind: Secret
metadata:
    creationTimestamp: null
    name: ldap-credentials
    namespace: gitlab
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-06-16T08:12:18Z"
    mac: ...
    pgp:
        - created_at: "2023-06-16T08:12:09Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA97+BPKHpJmVARAApkUnqWs+iChoPNt3l7TzsKRNDaL+qM0uBPLM2ArINc6+
            ...
            v09Qxru9pw==
            =rtWS
            -----END PGP MESSAGE-----
          fp: ...
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
