#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:yaml", "yaml")
---
#! GIT SECRET
apiVersion: v1
kind: Secret
metadata:
  name: cyan
  namespace: cyan
stringData:
  caFile: #@ data.values.other.sensitive_values.ca_cert_data
  password: #@ data.values.other.sensitive_values.teams.teal.git.password
  username: #@ data.values.other.sensitive_values.teams.teal.git.username
---
---
apiVersion: v1
kind: Secret
metadata:
  name: repo-auth
  namespace: cyan
stringData:
  caFile: #@ data.values.other.sensitive_values.ca_cert_data
  password: #@ data.values.other.sensitive_values.teams.teal.helm.password
  username: #@ data.values.other.sensitive_values.teams.teal.helm.username

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cyan
  namespace: apps
spec:
  interval: 5m0s
  path: ./teams/cyan/staging
  prune: true
  targetNamespace: cyan
  sourceRef:
    kind: GitRepository
    name: apps

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-controller-flux-system-cyan-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crd-controller-flux-system
subjects:
- kind: ServiceAccount
  name: default
  namespace: cyan
