apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven-test-containers
  description: Run Tests
spec:
  workspaces:
    - name: output
      description: The workspace consisting of maven project.
  steps:
    - name: read
      image: harbor.services.mydomain.com/dh-proxy/library/eclipse-temurin:17.0.3_7-jdk-alpine
      workingDir: $(workspaces.output.path)
      script: ./mvnw test
      volumeMounts:
        - mountPath: /var/run/
          name: dind-socket
  sidecars:
    - image: harbor.services.mydomain.com/dh-proxy/library/docker:20.10-dind
      name: docker
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/docker
          name: dind-storage
        - mountPath: /var/run/
          name: dind-socket
  volumes:
    - name: dind-storage
      emptyDir: { }
    - name: dind-socket
      emptyDir: { }