
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  timeout: 25m0s
  chart:
    spec:
      chart: grafana
      version: "9.0.5"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: default
      interval: 5m
  values:
    global:
      imageRegistry: harbor.services.mydomain.com/dh-proxy
    admin:
      password: "REPLACE_ME"
    ingress:
      enabled: true
      hostname: grafana.services.mydomain.com
      ingressClassName: contour