apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: psql
  namespace: auth
spec:
  interval: 5m
  timeout: 10m0s
  chart:
    spec:
      chart: postgresql
      version: "12.5.7"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: default
      interval: 5m
  values:
    global:
      imageRegistry: harbor.services.mydomain.com
      postgresql:
        auth:
          username: keycloakadmin
          database: bitnami_keycloak
          existingSecret: keycloak-credentials
          secretKeys:
            adminPasswordKey: password
            userPasswordKey: password
    image:
      repository: dh-proxy/bitnami/postgresql
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: auth
spec:
  interval: 5m
  timeout: 10m0s
  chart:
    spec:
      chart: keycloak
      version: "15.1.3"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: default
      interval: 5m
  values:
    global:
      imageRegistry: harbor.services.mydomain.com
    image:
      repository: dh-proxy/bitnami/keycloak
    keycloakConfigCli:
      image:
        repository: dh-proxy/bitnami/keycloak-config-cli
    auth:
      adminUser: keycloakadmin
      existingSecret: keycloak-credentials
      passwordSecretKey: password
    service:
      type: ClusterIP
    ingress:
      enabled: false
    postgresql:
      enabled: false
    externalDatabase:
      host: psql-postgresql
      database: bitnami_keycloak
      user: keycloakadmin
      existingSecret: keycloak-credentials
      existingSecretPasswordKey: password
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: keycloak
  namespace: auth
spec:
  ingressClassName: contour
  virtualhost:
    fqdn: keycloak.services.mydomain.com
    tls:
      secretName: keycloak-tls
  routes:
  - services:
    - name: keycloak
      port: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak
  namespace: auth
spec:
  secretName: keycloak-tls
  issuerRef:
    name: vault-issuer
    kind: "ClusterIssuer"
  commonName: keycloak.services.mydomain.com
  dnsNames:
  - keycloak.services.mydomain.com
---