apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 5m
  timeout: 25m0s
  chart:
    spec:
      chart: minio
      version: "12.6.4"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: default
      interval: 5m
  values:
    global:
      imageRegistry: harbor.services.mydomain.com
      storageClass: default
    image:
      repository: dh-proxy/bitnami/minio
    clientImage:
      repository: dh-proxy/bitnami/minio-client
    volumePermissions:
      image:
        repository: dh-proxy/bitnami/bitnami-shell
    auth:
      existingSecret: minio-credentials
    mode: distributed
    statefulset:
      replicaCount: 4
    # service:
    #   annotations:
    #     projectcontour.io/upstream-protocol.tls: "9000,9001"
    # ingress:
    #   tls:
    #     enabled: true
    #     existingSecret: minio-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio
  namespace: minio
spec:
  secretName: minio-tls
  issuerRef:
    name: vault-issuer
    kind: "ClusterIssuer"
  commonName: minio.services.mydomain.com
  dnsNames:
  - minio.services.mydomain.com
  - minio-console.services.mydomain.com
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: minio-console
  namespace: minio
spec:
  ingressClassName: contour
  virtualhost:
    fqdn: minio-console.services.mydomain.com
    tls:
      secretName: minio-tls
  routes:
  - services:
    - name: minio
      port: 9000
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: minio-insecure
  namespace: minio
spec:
  ingressClassName: contour
  virtualhost:
    fqdn: minio-insecure.services.mydomain.com
  routes:
  - services:
    - name: minio
      port: 9000
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: minio-api
  namespace: minio
spec:
  ingressClassName: contour
  virtualhost:
    fqdn: minio.services.mydomain.com
    tls:
      secretName: minio-tls
  routes:
  - services:
    - name: minio
      port: 9001

