apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: psql
  namespace: sonar
spec:
  interval: 5m
  timeout: 10m0s
  chart:
    spec:
      chart: postgresql
      version: "12.5.7"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: default
      interval: 5m
  values:
    global:
      imageRegistry: harbor.services.mydomain.com
      postgresql:
        auth:
          username: sonaradmin
          database: sonarqube
          existingSecret: sonar-credentials
          secretKeys:
            adminPasswordKey: password
            userPasswordKey: password
    image:
      repository: dh-proxy/bitnami/postgresql
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonar
  namespace: sonar
spec:
  interval: 5m
  timeout: 10m0s
  chart:
    spec:
      chart: sonarqube
      version: "8.0.1+546"
      sourceRef:
        kind: HelmRepository
        name: sonarqube
        namespace: default
      interval: 5m
  values:
    existingSecret: sonar-credentials
    global:
      imageRegistry: harbor.services.mydomain.com
    image:
      repository: dh-proxy/bitnami/sonarqube
    caCerts:
      image:
        repository: dh-proxy/bitnami/bitnami-shell
    volumePermissions:
      image:
        repository: dh-proxy/bitnami/bitnami-shell
    sysctl:
      image:
        repository: dh-proxy/bitnami/bitnami-shell
    ingress:
      enabled: false
    service:
      type: ClusterIP
    resources:
      limits:
        cpu: 1000m
        memory: 4096Mi
    plugins:
      image:
        repository: dh-proxy/bitnami/bitnami-shell
      install:
        - https://github.com/sonargraph/sonar-sonargraph-integration/releases/download/Release-4.1.2/sonar-sonargraph-integration-4.1.2.jar
        - https://github.com/dependency-check/dependency-check-sonar-plugin/releases/download/3.1.0/sonar-dependency-check-plugin-3.1.0.jar
        - https://github.com/vaulttec/sonar-auth-oidc/releases/download/v2.1.1/sonar-auth-oidc-plugin-2.1.1.jar
        - https://github.com/sbaudoin/sonar-shellcheck/releases/download/v2.5.0/sonar-shellcheck-plugin-2.5.0.jar
        - https://github.com/spotbugs/sonar-findbugs/releases/download/4.2.3/sonar-findbugs-plugin-4.2.3.jar
        - https://github.com/jborgers/sonar-pmd/releases/download/3.4.0/sonar-pmd-plugin-3.4.0.jar
    postgresql:
      enabled: false
    externalDatabase:
      host: psql-postgresql
      database: sonarqube
      user: keycloakadmin
      existingSecret: sonar-credentials
      existingSecretPasswordKey: password
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: sonar
  namespace: sonar
spec:
  ingressClassName: contour
  virtualhost:
    fqdn: sonar.services.mydomain.com
    tls:
      secretName: sonar-tls
  routes:
  - services:
    - name: sonar
      port: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonar
  namespace: sonar
spec:
  secretName: sonar-tls
  issuerRef:
    name: vault-issuer
    kind: "ClusterIssuer"
  commonName: sonar.services.mydomain.com
  dnsNames:
  - sonar.services.mydomain.com
---