
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  interval: 5m
  timeout: 25m0s
  chart:
    spec:
      chart: thanos
      version: "12.9.1"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: default
      interval: 5m
  values:
    global:
      imageRegistry: harbor.services.mydomain.com/dh-proxy
    objstoreConfig: |-
      type: s3
      config:
        bucket: thanos
        endpoint: {{ include "thanos.minio.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:9000
        access_key: minio
        secret_key: minio123
        insecure: true
    query:
      stores:
        - "thanos.build.mydomain.com:80"
        - "thanos.run-01.mydomain.com:80"
        - "thanos.run-02.mydomain.com:80"
    queryFrontend:
      enabled: true
      ingress:
        enabled: true
        hostname: thanos.services.mydomain.com
        ingressClassName: contour
    bucketweb:
      enabled: true
    compactor:
      enabled: true
    storegateway:
      enabled: true
    ruler:
      enabled: true
      alertmanagers:
        - http://prometheus-operator-alertmanager.monitoring.svc.cluster.local:9093
      config: |-
        groups:
          - name: "metamonitoring"
            rules:
              - alert: "PrometheusDown"
                expr: absent(up{prometheus="monitoring/prometheus-operator"})
    metrics:
      enabled: true
      serviceMonitor:
        enabled: false
    minio:
      enabled: true
      auth:
        rootPassword: minio123
        rootUser: minio
      monitoringBuckets: thanos
      accessKey:
        password: minio
      secretKey:
        password: minio123