apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 5m
  chart:
    spec:
      chart: vault
      version: "0.24.1"
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: default
      interval: 1m
  values:
    server:
      dataStorage:
        storageClass: default
      affinity: ""
      ha:
        enabled: true
        raft: 
          enabled: true
    ui:
      enabled: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: issuer
  namespace: cert-manager
---
apiVersion: v1
kind: Secret
metadata:
  name: issuer-token-lmzpj
  namespace: cert-manager
  annotations:
    kubernetes.io/service-account.name: issuer
type: kubernetes.io/service-account-token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
  namespace: cert-manager
spec:
  vault:
    server: http://vault.vault.svc.cluster.local:8200
    path: pki/sign/h2o13047
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: issuer
        secretRef:
          name: issuer-token-lmzpj
          key: token
